### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  commentId: T:Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  id: ApplicationEnvironment
  parent: Microsoft.Extensions.PlatformAbstractions
  children:
  - Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationBasePath
  - Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationName
  - Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationVersion
  - Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.RuntimeFramework
  langs:
  - csharp
  - vb
  name: ApplicationEnvironment
  nameWithType: ApplicationEnvironment
  fullName: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/PlatformAbstractions.git
    id: ApplicationEnvironment
    path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.PlatformAbstractions
  namespace: Microsoft.Extensions.PlatformAbstractions
  syntax:
    content: public class ApplicationEnvironment
    content.vb: Public Class ApplicationEnvironment
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationBasePath
  commentId: P:Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationBasePath
  id: ApplicationBasePath
  parent: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  langs:
  - csharp
  - vb
  name: ApplicationBasePath
  nameWithType: ApplicationEnvironment.ApplicationBasePath
  fullName: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationBasePath
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/PlatformAbstractions.git
    id: ApplicationBasePath
    path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
    startLine: 12
  assemblies:
  - Microsoft.Extensions.PlatformAbstractions
  namespace: Microsoft.Extensions.PlatformAbstractions
  syntax:
    content: public string ApplicationBasePath { get; }
    content.vb: Public ReadOnly Property ApplicationBasePath As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationName
  commentId: P:Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationName
  id: ApplicationName
  parent: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  langs:
  - csharp
  - vb
  name: ApplicationName
  nameWithType: ApplicationEnvironment.ApplicationName
  fullName: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationName
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/PlatformAbstractions.git
    id: ApplicationName
    path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
    startLine: 14
  assemblies:
  - Microsoft.Extensions.PlatformAbstractions
  namespace: Microsoft.Extensions.PlatformAbstractions
  syntax:
    content: public string ApplicationName { get; }
    content.vb: Public ReadOnly Property ApplicationName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationVersion
  commentId: P:Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationVersion
  id: ApplicationVersion
  parent: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  langs:
  - csharp
  - vb
  name: ApplicationVersion
  nameWithType: ApplicationEnvironment.ApplicationVersion
  fullName: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.ApplicationVersion
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/PlatformAbstractions.git
    id: ApplicationVersion
    path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
    startLine: 16
  assemblies:
  - Microsoft.Extensions.PlatformAbstractions
  namespace: Microsoft.Extensions.PlatformAbstractions
  syntax:
    content: public string ApplicationVersion { get; }
    content.vb: Public ReadOnly Property ApplicationVersion As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.RuntimeFramework
  commentId: P:Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.RuntimeFramework
  id: RuntimeFramework
  parent: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment
  langs:
  - csharp
  - vb
  name: RuntimeFramework
  nameWithType: ApplicationEnvironment.RuntimeFramework
  fullName: Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.RuntimeFramework
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/PlatformAbstractions.git
    id: RuntimeFramework
    path: src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs
    startLine: 18
  assemblies:
  - Microsoft.Extensions.PlatformAbstractions
  namespace: Microsoft.Extensions.PlatformAbstractions
  syntax:
    content: public FrameworkName RuntimeFramework { get; }
    content.vb: Public ReadOnly Property RuntimeFramework As FrameworkName
    parameters: []
    return:
      type: System.Runtime.Versioning.FrameworkName
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Microsoft.Extensions.PlatformAbstractions
  commentId: N:Microsoft.Extensions.PlatformAbstractions
  isExternal: false
  name: Microsoft.Extensions.PlatformAbstractions
  nameWithType: Microsoft.Extensions.PlatformAbstractions
  fullName: Microsoft.Extensions.PlatformAbstractions
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Versioning.FrameworkName
  commentId: T:System.Runtime.Versioning.FrameworkName
  parent: System.Runtime.Versioning
  isExternal: true
  name: FrameworkName
  nameWithType: FrameworkName
  fullName: System.Runtime.Versioning.FrameworkName
- uid: System.Runtime.Versioning
  commentId: N:System.Runtime.Versioning
  isExternal: false
  name: System.Runtime.Versioning
  nameWithType: System.Runtime.Versioning
  fullName: System.Runtime.Versioning
