### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  id: IAuthenticatedEncryptorDescriptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  children:
  - Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance
  - Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml
  langs:
  - csharp
  - vb
  name: IAuthenticatedEncryptorDescriptor
  nameWithType: IAuthenticatedEncryptorDescriptor
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
      branch: master
      repo: https://github.com/aspnet/DataProtection.git
    id: IAuthenticatedEncryptorDescriptor
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nA self-contained descriptor that wraps all information (including secret key\nmaterial) necessary to create an instance of an <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public interface IAuthenticatedEncryptorDescriptor
    content.vb: Public Interface IAuthenticatedEncryptorDescriptor
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance
  id: CreateEncryptorInstance
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  langs:
  - csharp
  - vb
  name: CreateEncryptorInstance()
  nameWithType: IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance()
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance()
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
      branch: master
      repo: https://github.com/aspnet/DataProtection.git
    id: CreateEncryptorInstance
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
    startLine: 23
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nCreates an <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor\" data-throw-if-not-resolved=\"false\"></xref> instance based on the current descriptor.\n"
  remarks: "\nFor a given descriptor, any two instances returned by this method should\nbe considered equivalent, e.g., the payload returned by one's <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment%7bSystem.Byte%7d%2cSystem.ArraySegment%7bSystem.Byte%7d)\" data-throw-if-not-resolved=\"false\"></xref>\nmethod should be consumable by the other's <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment%7bSystem.Byte%7d%2cSystem.ArraySegment%7bSystem.Byte%7d)\" data-throw-if-not-resolved=\"false\"></xref> method.\n"
  example: []
  syntax:
    content: IAuthenticatedEncryptor CreateEncryptorInstance()
    content.vb: Function CreateEncryptorInstance As IAuthenticatedEncryptor
    return:
      type: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
      description: An <xref href="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor" data-throw-if-not-resolved="false"></xref> instance.
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml
  id: ExportToXml
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  langs:
  - csharp
  - vb
  name: ExportToXml()
  nameWithType: IAuthenticatedEncryptorDescriptor.ExportToXml()
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml()
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
      branch: master
      repo: https://github.com/aspnet/DataProtection.git
    id: ExportToXml
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
    startLine: 38
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nExports the current descriptor to XML.\n"
  remarks: "\nIf an element contains sensitive information (such as key material), the\nelement should be marked via the <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlExtensions.MarkAsRequiresEncryption(System.Xml.Linq.XElement)\" data-throw-if-not-resolved=\"false\"></xref>\nextension method, and the caller should encrypt the element before persisting\nthe XML to storage.\n"
  example: []
  syntax:
    content: XmlSerializedDescriptorInfo ExportToXml()
    content.vb: Function ExportToXml As XmlSerializedDescriptorInfo
    return:
      type: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
      description: "\nAn <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo\" data-throw-if-not-resolved=\"false\"></xref> wrapping the <xref href=\"System.Xml.Linq.XElement\" data-throw-if-not-resolved=\"false\"></xref> which represents the serialized\ncurrent descriptor object. The deserializer type must be assignable to <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer\" data-throw-if-not-resolved=\"false\"></xref>.\n"
references:
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  isExternal: false
  name: IAuthenticatedEncryptor
  nameWithType: IAuthenticatedEncryptor
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  commentId: N:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  nameWithType: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  commentId: N:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  isExternal: false
  name: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  nameWithType: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
  isExternal: true
  name: Encrypt(ArraySegment<Byte>, ArraySegment<Byte>)
  nameWithType: IAuthenticatedEncryptor.Encrypt(ArraySegment<Byte>, ArraySegment<Byte>)
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment<System.Byte>, System.ArraySegment<System.Byte>)
  nameWithType.vb: IAuthenticatedEncryptor.Encrypt(ArraySegment(Of Byte), ArraySegment(Of Byte))
  fullname.vb: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment(Of System.Byte), System.ArraySegment(Of System.Byte))
  name.vb: Encrypt(ArraySegment(Of Byte), ArraySegment(Of Byte))
  spec.csharp:
  - uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
    name: Encrypt
    nameWithType: IAuthenticatedEncryptor.Encrypt
    fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
    name: Encrypt
    nameWithType: IAuthenticatedEncryptor.Encrypt
    fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
  isExternal: true
  name: Decrypt(ArraySegment<Byte>, ArraySegment<Byte>)
  nameWithType: IAuthenticatedEncryptor.Decrypt(ArraySegment<Byte>, ArraySegment<Byte>)
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment<System.Byte>, System.ArraySegment<System.Byte>)
  nameWithType.vb: IAuthenticatedEncryptor.Decrypt(ArraySegment(Of Byte), ArraySegment(Of Byte))
  fullname.vb: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment(Of System.Byte), System.ArraySegment(Of System.Byte))
  name.vb: Decrypt(ArraySegment(Of Byte), ArraySegment(Of Byte))
  spec.csharp:
  - uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
    name: Decrypt
    nameWithType: IAuthenticatedEncryptor.Decrypt
    fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})
    name: Decrypt
    nameWithType: IAuthenticatedEncryptor.Decrypt
    fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.ArraySegment`1
    name: ArraySegment
    nameWithType: ArraySegment
    fullName: System.ArraySegment
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: XmlSerializedDescriptorInfo
  nameWithType: XmlSerializedDescriptorInfo
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
- uid: System.Xml.Linq.XElement
  commentId: T:System.Xml.Linq.XElement
  parent: System.Xml.Linq
  isExternal: true
  name: XElement
  nameWithType: XElement
  fullName: System.Xml.Linq.XElement
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: IAuthenticatedEncryptorDescriptorDeserializer
  nameWithType: IAuthenticatedEncryptorDescriptorDeserializer
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlExtensions.MarkAsRequiresEncryption(System.Xml.Linq.XElement)
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlExtensions.MarkAsRequiresEncryption(System.Xml.Linq.XElement)
- uid: System.Xml.Linq
  commentId: N:System.Xml.Linq
  isExternal: false
  name: System.Xml.Linq
  nameWithType: System.Xml.Linq
  fullName: System.Xml.Linq
