### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  id: IAuthenticatedEncryptorConfiguration
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  children:
  - Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  langs:
  - csharp
  - vb
  name: IAuthenticatedEncryptorConfiguration
  nameWithType: IAuthenticatedEncryptorConfiguration
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/DataProtection.git
    id: IAuthenticatedEncryptorConfiguration
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorConfiguration.cs
    startLine: 10
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nThe basic configuration that serves as a factory for types related to authenticated encryption.\n"
  example: []
  syntax:
    content: public interface IAuthenticatedEncryptorConfiguration
    content.vb: Public Interface IAuthenticatedEncryptorConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  id: CreateNewDescriptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  langs:
  - csharp
  - vb
  name: CreateNewDescriptor()
  nameWithType: IAuthenticatedEncryptorConfiguration.CreateNewDescriptor()
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor()
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/DataProtection.git
    id: CreateNewDescriptor
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorConfiguration.cs
    startLine: 18
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nCreates a new <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor\" data-throw-if-not-resolved=\"false\"></xref> instance based on this\nconfiguration. The newly-created instance contains unique key material and is distinct\nfrom all other descriptors created by the <xref href=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor\" data-throw-if-not-resolved=\"false\"></xref> method.\n"
  example: []
  syntax:
    content: IAuthenticatedEncryptorDescriptor CreateNewDescriptor()
    content.vb: Function CreateNewDescriptor As IAuthenticatedEncryptorDescriptor
    return:
      type: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
      description: A unique <xref href="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor" data-throw-if-not-resolved="false"></xref>.
references:
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  commentId: N:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  nameWithType: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: IAuthenticatedEncryptorDescriptor
  nameWithType: IAuthenticatedEncryptorDescriptor
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  isExternal: false
  name: CreateNewDescriptor()
  nameWithType: IAuthenticatedEncryptorConfiguration.CreateNewDescriptor()
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor()
  spec.csharp:
  - uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
    name: CreateNewDescriptor
    nameWithType: IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
    fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
    name: CreateNewDescriptor
    nameWithType: IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
    fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration.CreateNewDescriptor
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: IAuthenticatedEncryptorConfiguration
  nameWithType: IAuthenticatedEncryptorConfiguration
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorConfiguration
