### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature
  commentId: T:Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature
  id: IOwinEnvironmentFeature
  parent: Microsoft.AspNetCore.Owin
  children:
  - Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature.Environment
  langs:
  - csharp
  - vb
  name: IOwinEnvironmentFeature
  nameWithType: IOwinEnvironmentFeature
  fullName: Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Owin/IOwinEnvironmentFeature.cs
      branch: master
      repo: https://github.com/aspnet/HttpAbstractions.git
    id: IOwinEnvironmentFeature
    path: src/Microsoft.AspNetCore.Owin/IOwinEnvironmentFeature.cs
    startLine: 7
  assemblies:
  - Microsoft.AspNetCore.Owin
  namespace: Microsoft.AspNetCore.Owin
  syntax:
    content: public interface IOwinEnvironmentFeature
    content.vb: Public Interface IOwinEnvironmentFeature
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature.Environment
  commentId: P:Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature.Environment
  id: Environment
  parent: Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature
  langs:
  - csharp
  - vb
  name: Environment
  nameWithType: IOwinEnvironmentFeature.Environment
  fullName: Microsoft.AspNetCore.Owin.IOwinEnvironmentFeature.Environment
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Owin/IOwinEnvironmentFeature.cs
      branch: master
      repo: https://github.com/aspnet/HttpAbstractions.git
    id: Environment
    path: src/Microsoft.AspNetCore.Owin/IOwinEnvironmentFeature.cs
    startLine: 9
  assemblies:
  - Microsoft.AspNetCore.Owin
  namespace: Microsoft.AspNetCore.Owin
  syntax:
    content: IDictionary<string, object> Environment { get; set; }
    content.vb: Property Environment As IDictionary(Of String, Object)
    parameters: []
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
  modifiers.csharp:
  - get
  - set
references:
- uid: Microsoft.AspNetCore.Owin
  commentId: N:Microsoft.AspNetCore.Owin
  isExternal: false
  name: Microsoft.AspNetCore.Owin
  nameWithType: Microsoft.AspNetCore.Owin
  fullName: Microsoft.AspNetCore.Owin
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  commentId: T:System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  name: IDictionary<String, Object>
  nameWithType: IDictionary<String, Object>
  fullName: System.Collections.Generic.IDictionary<System.String, System.Object>
  nameWithType.vb: IDictionary(Of String, Object)
  fullname.vb: System.Collections.Generic.IDictionary(Of System.String, System.Object)
  name.vb: IDictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IDictionary`2
  commentId: T:System.Collections.Generic.IDictionary`2
  isExternal: true
  name: IDictionary<TKey, TValue>
  nameWithType: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  nameWithType.vb: IDictionary(Of TKey, TValue)
  fullname.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
