### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Options.IConfigureOptions`1
  commentId: T:Microsoft.Extensions.Options.IConfigureOptions`1
  id: IConfigureOptions`1
  parent: Microsoft.Extensions.Options
  children:
  - Microsoft.Extensions.Options.IConfigureOptions`1.Configure(`0)
  langs:
  - csharp
  - vb
  name: IConfigureOptions<TOptions>
  nameWithType: IConfigureOptions<TOptions>
  fullName: Microsoft.Extensions.Options.IConfigureOptions<TOptions>
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Options/IConfigureOptions.cs
      branch: master
      repo: https://github.com/aspnet/Options.git
    id: IConfigureOptions
    path: src/Microsoft.Extensions.Options/IConfigureOptions.cs
    startLine: 9
  assemblies:
  - Microsoft.Extensions.Options
  namespace: Microsoft.Extensions.Options
  summary: "\nRepresents something that configures the TOptions type.\n"
  example: []
  syntax:
    content: >-
      public interface IConfigureOptions<in TOptions>
          where TOptions : class
    content.vb: Public Interface IConfigureOptions(Of In TOptions As Class)
    typeParameters:
    - id: TOptions
      description: ''
  nameWithType.vb: IConfigureOptions(Of TOptions)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Extensions.Options.IConfigureOptions(Of TOptions)
  name.vb: IConfigureOptions(Of TOptions)
- uid: Microsoft.Extensions.Options.IConfigureOptions`1.Configure(`0)
  commentId: M:Microsoft.Extensions.Options.IConfigureOptions`1.Configure(`0)
  id: Configure(`0)
  parent: Microsoft.Extensions.Options.IConfigureOptions`1
  langs:
  - csharp
  - vb
  name: Configure(TOptions)
  nameWithType: IConfigureOptions<TOptions>.Configure(TOptions)
  fullName: Microsoft.Extensions.Options.IConfigureOptions<TOptions>.Configure(TOptions)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Options/IConfigureOptions.cs
      branch: master
      repo: https://github.com/aspnet/Options.git
    id: Configure
    path: src/Microsoft.Extensions.Options/IConfigureOptions.cs
    startLine: 15
  assemblies:
  - Microsoft.Extensions.Options
  namespace: Microsoft.Extensions.Options
  summary: "\nInvoked to configure a TOptions instance.\n"
  example: []
  syntax:
    content: void Configure(TOptions options)
    content.vb: Sub Configure(options As TOptions)
    parameters:
    - id: options
      type: '{TOptions}'
      description: The options instance to configure.
  nameWithType.vb: IConfigureOptions(Of TOptions).Configure(TOptions)
  fullName.vb: Microsoft.Extensions.Options.IConfigureOptions(Of TOptions).Configure(TOptions)
references:
- uid: Microsoft.Extensions.Options
  commentId: N:Microsoft.Extensions.Options
  isExternal: false
  name: Microsoft.Extensions.Options
  nameWithType: Microsoft.Extensions.Options
  fullName: Microsoft.Extensions.Options
- uid: '{TOptions}'
  commentId: '!:TOptions'
  definition: TOptions
  name: TOptions
  nameWithType: TOptions
  fullName: TOptions
- uid: TOptions
  isExternal: false
  name: TOptions
  nameWithType: TOptions
  fullName: TOptions
