### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  id: Microsoft.Extensions.Configuration.Json
  children:
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Json
references:
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  isExternal: false
  name: JsonConfigurationProvider
  nameWithType: JsonConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  parent: Microsoft.Extensions.Configuration.Json
  isExternal: false
  name: JsonConfigurationSource
  nameWithType: JsonConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  isExternal: false
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
