### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.FunctionalTests
  commentId: N:Microsoft.Extensions.Configuration.FunctionalTests
  id: Microsoft.Extensions.Configuration.FunctionalTests
  children:
  - Microsoft.Extensions.Configuration.FunctionalTests.ArrayTests
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.FunctionalTests
  nameWithType: Microsoft.Extensions.Configuration.FunctionalTests
  fullName: Microsoft.Extensions.Configuration.FunctionalTests
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.FunctionalTests
references:
- uid: Microsoft.Extensions.Configuration.FunctionalTests.ArrayTests
  commentId: T:Microsoft.Extensions.Configuration.FunctionalTests.ArrayTests
  isExternal: false
  name: ArrayTests
  nameWithType: ArrayTests
  fullName: Microsoft.Extensions.Configuration.FunctionalTests.ArrayTests
