### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Test
  commentId: N:Microsoft.Extensions.Configuration.Test
  id: Microsoft.Extensions.Configuration.Test
  children:
  - Microsoft.Extensions.Configuration.Test.ConfigurationPathComparerTest
  - Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  - Microsoft.Extensions.Configuration.Test.ConfigurationProviderExtensions
  - Microsoft.Extensions.Configuration.Test.ConfigurationTest
  - Microsoft.Extensions.Configuration.Test.ConfigurationTest.TestMemorySourceProvider
  - Microsoft.Extensions.Configuration.Test.ConfigurationTests
  - Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestIniSourceProvider
  - Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestJsonSourceProvider
  - Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestXmlSourceProvider
  - Microsoft.Extensions.Configuration.Test.TestStreamHelpers
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Test
  nameWithType: Microsoft.Extensions.Configuration.Test
  fullName: Microsoft.Extensions.Configuration.Test
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Test.Common
references:
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationProviderExtensions
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationProviderExtensions
  parent: Microsoft.Extensions.Configuration.Test
  isExternal: false
  name: ConfigurationProviderExtensions
  nameWithType: ConfigurationProviderExtensions
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationProviderExtensions
- uid: Microsoft.Extensions.Configuration.Test.TestStreamHelpers
  commentId: T:Microsoft.Extensions.Configuration.Test.TestStreamHelpers
  isExternal: false
  name: TestStreamHelpers
  nameWithType: TestStreamHelpers
  fullName: Microsoft.Extensions.Configuration.Test.TestStreamHelpers
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationPathComparerTest
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationPathComparerTest
  isExternal: false
  name: ConfigurationPathComparerTest
  nameWithType: ConfigurationPathComparerTest
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationPathComparerTest
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  isExternal: false
  name: ConfigurationPathTest
  nameWithType: ConfigurationPathTest
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationTest
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationTest
  isExternal: false
  name: ConfigurationTest
  nameWithType: ConfigurationTest
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationTest
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationTest.TestMemorySourceProvider
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationTest.TestMemorySourceProvider
  isExternal: false
  name: ConfigurationTest.TestMemorySourceProvider
  nameWithType: ConfigurationTest.TestMemorySourceProvider
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationTest.TestMemorySourceProvider
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationTests
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationTests
  isExternal: false
  name: ConfigurationTests
  nameWithType: ConfigurationTests
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationTests
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestIniSourceProvider
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestIniSourceProvider
  isExternal: false
  name: ConfigurationTests.TestIniSourceProvider
  nameWithType: ConfigurationTests.TestIniSourceProvider
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestIniSourceProvider
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestJsonSourceProvider
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestJsonSourceProvider
  isExternal: false
  name: ConfigurationTests.TestJsonSourceProvider
  nameWithType: ConfigurationTests.TestJsonSourceProvider
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestJsonSourceProvider
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestXmlSourceProvider
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestXmlSourceProvider
  isExternal: false
  name: ConfigurationTests.TestXmlSourceProvider
  nameWithType: ConfigurationTests.TestXmlSourceProvider
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationTests.TestXmlSourceProvider
- uid: Microsoft.Extensions.Configuration.Test
  commentId: N:Microsoft.Extensions.Configuration.Test
  isExternal: false
  name: Microsoft.Extensions.Configuration.Test
  nameWithType: Microsoft.Extensions.Configuration.Test
  fullName: Microsoft.Extensions.Configuration.Test
