### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Ini
  commentId: N:Microsoft.Extensions.Configuration.Ini
  id: Microsoft.Extensions.Configuration.Ini
  children:
  - Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  - Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Ini
  nameWithType: Microsoft.Extensions.Configuration.Ini
  fullName: Microsoft.Extensions.Configuration.Ini
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Ini
references:
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  isExternal: false
  name: IniConfigurationProvider
  nameWithType: IniConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  parent: Microsoft.Extensions.Configuration.Ini
  isExternal: false
  name: IniConfigurationSource
  nameWithType: IniConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
- uid: Microsoft.Extensions.Configuration.Ini
  commentId: N:Microsoft.Extensions.Configuration.Ini
  isExternal: false
  name: Microsoft.Extensions.Configuration.Ini
  nameWithType: Microsoft.Extensions.Configuration.Ini
  fullName: Microsoft.Extensions.Configuration.Ini
