### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest
  commentId: T:Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest
  id: FileConfigurationBuilderExtensionsTest
  parent: Microsoft.Extensions.Configuration.Json
  children:
  - Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet
  - Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_CheckPropertiesValueOnBuilder
  - Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_ThrowsIfBasePathIsNull
  langs:
  - csharp
  - vb
  name: FileConfigurationBuilderExtensionsTest
  nameWithType: FileConfigurationBuilderExtensionsTest
  fullName: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest
  type: Class
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: FileConfigurationBuilderExtensionsTest
    path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions.Test
  namespace: Microsoft.Extensions.Configuration.Json
  syntax:
    content: public class FileConfigurationBuilderExtensionsTest
    content.vb: Public Class FileConfigurationBuilderExtensionsTest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_ThrowsIfBasePathIsNull
  commentId: M:Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_ThrowsIfBasePathIsNull
  id: SetFileProvider_ThrowsIfBasePathIsNull
  parent: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest
  langs:
  - csharp
  - vb
  name: SetFileProvider_ThrowsIfBasePathIsNull()
  nameWithType: FileConfigurationBuilderExtensionsTest.SetFileProvider_ThrowsIfBasePathIsNull()
  fullName: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_ThrowsIfBasePathIsNull()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: SetFileProvider_ThrowsIfBasePathIsNull
    path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
    startLine: 12
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions.Test
  namespace: Microsoft.Extensions.Configuration.Json
  syntax:
    content: >-
      [Fact]

      public void SetFileProvider_ThrowsIfBasePathIsNull()
    content.vb: >-
      <Fact>

      Public Sub SetFileProvider_ThrowsIfBasePathIsNull
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_CheckPropertiesValueOnBuilder
  commentId: M:Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_CheckPropertiesValueOnBuilder
  id: SetFileProvider_CheckPropertiesValueOnBuilder
  parent: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest
  langs:
  - csharp
  - vb
  name: SetFileProvider_CheckPropertiesValueOnBuilder()
  nameWithType: FileConfigurationBuilderExtensionsTest.SetFileProvider_CheckPropertiesValueOnBuilder()
  fullName: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.SetFileProvider_CheckPropertiesValueOnBuilder()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: SetFileProvider_CheckPropertiesValueOnBuilder
    path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
    startLine: 23
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions.Test
  namespace: Microsoft.Extensions.Configuration.Json
  syntax:
    content: >-
      [Fact]

      public void SetFileProvider_CheckPropertiesValueOnBuilder()
    content.vb: >-
      <Fact>

      Public Sub SetFileProvider_CheckPropertiesValueOnBuilder
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet
  commentId: M:Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet
  id: GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet
  parent: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest
  langs:
  - csharp
  - vb
  name: GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet()
  nameWithType: FileConfigurationBuilderExtensionsTest.GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet()
  fullName: Microsoft.Extensions.Configuration.Json.FileConfigurationBuilderExtensionsTest.GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet
    path: test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
    startLine: 35
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions.Test
  namespace: Microsoft.Extensions.Configuration.Json
  syntax:
    content: >-
      [Fact]

      public void GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet()
    content.vb: >-
      <Fact>

      Public Sub GetFileProvider_ReturnPhysicalProviderWithBaseDirectoryIfNotSet
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  isExternal: false
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
