### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.CommandLine
  commentId: N:Microsoft.Extensions.Configuration.CommandLine
  id: Microsoft.Extensions.Configuration.CommandLine
  children:
  - Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider
  - Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.CommandLine
  nameWithType: Microsoft.Extensions.Configuration.CommandLine
  fullName: Microsoft.Extensions.Configuration.CommandLine
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.CommandLine
references:
- uid: Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider
  isExternal: false
  name: CommandLineConfigurationProvider
  nameWithType: CommandLineConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider
- uid: Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationSource
  isExternal: false
  name: CommandLineConfigurationSource
  nameWithType: CommandLineConfigurationSource
  fullName: Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationSource
