### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Xml.Test
  commentId: N:Microsoft.Extensions.Configuration.Xml.Test
  id: Microsoft.Extensions.Configuration.Xml.Test
  children:
  - Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationExtensionsTest
  - Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationTest
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Xml.Test
  nameWithType: Microsoft.Extensions.Configuration.Xml.Test
  fullName: Microsoft.Extensions.Configuration.Xml.Test
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Xml.Test
references:
- uid: Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationExtensionsTest
  commentId: T:Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationExtensionsTest
  isExternal: false
  name: XmlConfigurationExtensionsTest
  nameWithType: XmlConfigurationExtensionsTest
  fullName: Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationExtensionsTest
- uid: Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationTest
  commentId: T:Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationTest
  isExternal: false
  name: XmlConfigurationTest
  nameWithType: XmlConfigurationTest
  fullName: Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationTest
