### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Binder.Test
  commentId: N:Microsoft.Extensions.Configuration.Binder.Test
  id: Microsoft.Extensions.Configuration.Binder.Test
  children:
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ConfigurationInterfaceOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.EnumOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions`1
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NestedOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NullableOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationCollectionBinding
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Binder.Test
  nameWithType: Microsoft.Extensions.Configuration.Binder.Test
  fullName: Microsoft.Extensions.Configuration.Binder.Test
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Binder.Test
references:
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests
  isExternal: false
  name: ConfigurationBinderTests
  nameWithType: ConfigurationBinderTests
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  parent: Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: ConfigurationBinderTests.ComplexOptions
  nameWithType: ConfigurationBinderTests.ComplexOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NestedOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NestedOptions
  parent: Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: ConfigurationBinderTests.NestedOptions
  nameWithType: ConfigurationBinderTests.NestedOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NestedOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  parent: Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: ConfigurationBinderTests.DerivedOptions
  nameWithType: ConfigurationBinderTests.DerivedOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NullableOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NullableOptions
  isExternal: false
  name: ConfigurationBinderTests.NullableOptions
  nameWithType: ConfigurationBinderTests.NullableOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.NullableOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.EnumOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.EnumOptions
  isExternal: false
  name: ConfigurationBinderTests.EnumOptions
  nameWithType: ConfigurationBinderTests.EnumOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.EnumOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions`1
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions`1
  isExternal: false
  name: ConfigurationBinderTests.GenericOptions<T>
  nameWithType: ConfigurationBinderTests.GenericOptions<T>
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions<T>
  nameWithType.vb: ConfigurationBinderTests.GenericOptions(Of T)
  fullname.vb: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions(Of T)
  name.vb: ConfigurationBinderTests.GenericOptions(Of T)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions`1
    name: ConfigurationBinderTests.GenericOptions
    nameWithType: ConfigurationBinderTests.GenericOptions
    fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions`1
    name: ConfigurationBinderTests.GenericOptions
    nameWithType: ConfigurationBinderTests.GenericOptions
    fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.GenericOptions
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ConfigurationInterfaceOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ConfigurationInterfaceOptions
  isExternal: false
  name: ConfigurationBinderTests.ConfigurationInterfaceOptions
  nameWithType: ConfigurationBinderTests.ConfigurationInterfaceOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ConfigurationInterfaceOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  isExternal: false
  name: ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  nameWithType: ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationCollectionBinding
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationCollectionBinding
  isExternal: false
  name: ConfigurationCollectionBinding
  nameWithType: ConfigurationCollectionBinding
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationCollectionBinding
- uid: Microsoft.Extensions.Configuration.Binder.Test
  commentId: N:Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: Microsoft.Extensions.Configuration.Binder.Test
  nameWithType: Microsoft.Extensions.Configuration.Binder.Test
  fullName: Microsoft.Extensions.Configuration.Binder.Test
