### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  commentId: T:Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  id: IniConfigurationExtensionsTest
  parent: Microsoft.Extensions.Configuration.Ini.Test
  children:
  - Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional
  - Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFileDoesNotExistAtPath
  - Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFilePathIsNullOrEmpty(System.String)
  langs:
  - csharp
  - vb
  name: IniConfigurationExtensionsTest
  nameWithType: IniConfigurationExtensionsTest
  fullName: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  type: Class
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: IniConfigurationExtensionsTest
    path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
    startLine: 9
  assemblies:
  - Microsoft.Extensions.Configuration.Ini.Test
  namespace: Microsoft.Extensions.Configuration.Ini.Test
  syntax:
    content: public class IniConfigurationExtensionsTest
    content.vb: Public Class IniConfigurationExtensionsTest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFilePathIsNullOrEmpty(System.String)
  commentId: M:Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFilePathIsNullOrEmpty(System.String)
  id: AddIniFile_ThrowsIfFilePathIsNullOrEmpty(System.String)
  parent: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  langs:
  - csharp
  - vb
  name: AddIniFile_ThrowsIfFilePathIsNullOrEmpty(String)
  nameWithType: IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFilePathIsNullOrEmpty(String)
  fullName: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFilePathIsNullOrEmpty(System.String)
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: AddIniFile_ThrowsIfFilePathIsNullOrEmpty
    path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
    startLine: 11
  assemblies:
  - Microsoft.Extensions.Configuration.Ini.Test
  namespace: Microsoft.Extensions.Configuration.Ini.Test
  syntax:
    content: >-
      [Theory]

      [InlineData(null)]

      [InlineData(new object[]{""})]

      public void AddIniFile_ThrowsIfFilePathIsNullOrEmpty(string path)
    content.vb: >-
      <Theory>

      <InlineData(Nothing)>

      <InlineData(New Object() {""})>

      Public Sub AddIniFile_ThrowsIfFilePathIsNullOrEmpty(path As String)
    parameters:
    - id: path
      type: System.String
  attributes:
  - type: Xunit.TheoryAttribute
    ctor: Xunit.TheoryAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFileDoesNotExistAtPath
  commentId: M:Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFileDoesNotExistAtPath
  id: AddIniFile_ThrowsIfFileDoesNotExistAtPath
  parent: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  langs:
  - csharp
  - vb
  name: AddIniFile_ThrowsIfFileDoesNotExistAtPath()
  nameWithType: IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFileDoesNotExistAtPath()
  fullName: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_ThrowsIfFileDoesNotExistAtPath()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: AddIniFile_ThrowsIfFileDoesNotExistAtPath
    path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
    startLine: 26
  assemblies:
  - Microsoft.Extensions.Configuration.Ini.Test
  namespace: Microsoft.Extensions.Configuration.Ini.Test
  syntax:
    content: >-
      [Fact]

      public void AddIniFile_ThrowsIfFileDoesNotExistAtPath()
    content.vb: >-
      <Fact>

      Public Sub AddIniFile_ThrowsIfFileDoesNotExistAtPath
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional
  commentId: M:Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional
  id: AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional
  parent: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  langs:
  - csharp
  - vb
  name: AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional()
  nameWithType: IniConfigurationExtensionsTest.AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional()
  fullName: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest.AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional
    path: test/Microsoft.Extensions.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
    startLine: 37
  assemblies:
  - Microsoft.Extensions.Configuration.Ini.Test
  namespace: Microsoft.Extensions.Configuration.Ini.Test
  syntax:
    content: >-
      [Fact]

      public void AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional()
    content.vb: >-
      <Fact>

      Public Sub AddIniFile_DoesNotThrowsIfFileDoesNotExistAtPathAndOptional
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration.Ini.Test
  commentId: N:Microsoft.Extensions.Configuration.Ini.Test
  isExternal: false
  name: Microsoft.Extensions.Configuration.Ini.Test
  nameWithType: Microsoft.Extensions.Configuration.Ini.Test
  fullName: Microsoft.Extensions.Configuration.Ini.Test
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
