### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Memory
  commentId: N:Microsoft.Extensions.Configuration.Memory
  id: Microsoft.Extensions.Configuration.Memory
  children:
  - Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  - Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Memory
  nameWithType: Microsoft.Extensions.Configuration.Memory
  fullName: Microsoft.Extensions.Configuration.Memory
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration
references:
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  isExternal: false
  name: MemoryConfigurationProvider
  nameWithType: MemoryConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  parent: Microsoft.Extensions.Configuration.Memory
  isExternal: false
  name: MemoryConfigurationSource
  nameWithType: MemoryConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
- uid: Microsoft.Extensions.Configuration.Memory
  commentId: N:Microsoft.Extensions.Configuration.Memory
  isExternal: false
  name: Microsoft.Extensions.Configuration.Memory
  nameWithType: Microsoft.Extensions.Configuration.Memory
  fullName: Microsoft.Extensions.Configuration.Memory
