### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  id: ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  parent: Microsoft.Extensions.Configuration.Binder.Test
  children:
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection.DerivedSection
  langs:
  - csharp
  - vb
  name: ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  nameWithType: ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  type: Class
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: DerivedOptionsWithIConfigurationSection
    path: test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs
    startLine: 80
  assemblies:
  - Microsoft.Extensions.Configuration.Binder.Test
  namespace: Microsoft.Extensions.Configuration.Binder.Test
  syntax:
    content: 'public class DerivedOptionsWithIConfigurationSection : ConfigurationBinderTests.DerivedOptions'
    content.vb: >-
      Public Class DerivedOptionsWithIConfigurationSection
          Inherits ConfigurationBinderTests.DerivedOptions
  inheritance:
  - System.Object
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  inheritedMembers:
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions.Virtual
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Nested
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Integer
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Boolean
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.PrivateSetter
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ProtectedSetter
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.InternalSetter
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.StaticProperty
  - Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ReadOnly
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection.DerivedSection
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection.DerivedSection
  id: DerivedSection
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection
  langs:
  - csharp
  - vb
  name: DerivedSection
  nameWithType: ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection.DerivedSection
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptionsWithIConfigurationSection.DerivedSection
  type: Property
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: DerivedSection
    path: test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs
    startLine: 82
  assemblies:
  - Microsoft.Extensions.Configuration.Binder.Test
  namespace: Microsoft.Extensions.Configuration.Binder.Test
  syntax:
    content: public IConfigurationSection DerivedSection { get; set; }
    content.vb: Public Property DerivedSection As IConfigurationSection
    parameters: []
    return:
      type: Microsoft.Extensions.Configuration.IConfigurationSection
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration.Binder.Test
  commentId: N:Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: Microsoft.Extensions.Configuration.Binder.Test
  nameWithType: Microsoft.Extensions.Configuration.Binder.Test
  fullName: Microsoft.Extensions.Configuration.Binder.Test
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  parent: Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: ConfigurationBinderTests.ComplexOptions
  nameWithType: ConfigurationBinderTests.ComplexOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  commentId: T:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  parent: Microsoft.Extensions.Configuration.Binder.Test
  isExternal: false
  name: ConfigurationBinderTests.DerivedOptions
  nameWithType: ConfigurationBinderTests.DerivedOptions
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions.Virtual
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions.Virtual
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions
  isExternal: false
  name: Virtual
  nameWithType: ConfigurationBinderTests.DerivedOptions.Virtual
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.DerivedOptions.Virtual
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Nested
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Nested
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: Nested
  nameWithType: ConfigurationBinderTests.ComplexOptions.Nested
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Nested
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Integer
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Integer
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: Integer
  nameWithType: ConfigurationBinderTests.ComplexOptions.Integer
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Integer
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Boolean
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Boolean
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: Boolean
  nameWithType: ConfigurationBinderTests.ComplexOptions.Boolean
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.Boolean
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.PrivateSetter
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.PrivateSetter
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: PrivateSetter
  nameWithType: ConfigurationBinderTests.ComplexOptions.PrivateSetter
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.PrivateSetter
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ProtectedSetter
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ProtectedSetter
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: ProtectedSetter
  nameWithType: ConfigurationBinderTests.ComplexOptions.ProtectedSetter
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ProtectedSetter
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.InternalSetter
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.InternalSetter
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: InternalSetter
  nameWithType: ConfigurationBinderTests.ComplexOptions.InternalSetter
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.InternalSetter
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.StaticProperty
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.StaticProperty
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: StaticProperty
  nameWithType: ConfigurationBinderTests.ComplexOptions.StaticProperty
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.StaticProperty
- uid: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ReadOnly
  commentId: P:Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ReadOnly
  parent: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions
  isExternal: false
  name: ReadOnly
  nameWithType: ConfigurationBinderTests.ComplexOptions.ReadOnly
  fullName: Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ComplexOptions.ReadOnly
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.IConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSection
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationSection
  nameWithType: IConfigurationSection
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
