### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Xml
  commentId: N:Microsoft.Extensions.Configuration.Xml
  id: Microsoft.Extensions.Configuration.Xml
  children:
  - Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  - Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  - Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Xml
  nameWithType: Microsoft.Extensions.Configuration.Xml
  fullName: Microsoft.Extensions.Configuration.Xml
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Xml
references:
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  isExternal: false
  name: XmlConfigurationProvider
  nameWithType: XmlConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  parent: Microsoft.Extensions.Configuration.Xml
  isExternal: false
  name: XmlConfigurationSource
  nameWithType: XmlConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
- uid: Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor
  parent: Microsoft.Extensions.Configuration.Xml
  isExternal: false
  name: XmlDocumentDecryptor
  nameWithType: XmlDocumentDecryptor
  fullName: Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor
- uid: Microsoft.Extensions.Configuration.Xml
  commentId: N:Microsoft.Extensions.Configuration.Xml
  isExternal: false
  name: Microsoft.Extensions.Configuration.Xml
  nameWithType: Microsoft.Extensions.Configuration.Xml
  fullName: Microsoft.Extensions.Configuration.Xml
