### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Ini.Test
  commentId: N:Microsoft.Extensions.Configuration.Ini.Test
  id: Microsoft.Extensions.Configuration.Ini.Test
  children:
  - Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  - Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationTest
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Ini.Test
  nameWithType: Microsoft.Extensions.Configuration.Ini.Test
  fullName: Microsoft.Extensions.Configuration.Ini.Test
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Ini.Test
references:
- uid: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  commentId: T:Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
  isExternal: false
  name: IniConfigurationExtensionsTest
  nameWithType: IniConfigurationExtensionsTest
  fullName: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationExtensionsTest
- uid: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationTest
  commentId: T:Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationTest
  isExternal: false
  name: IniConfigurationTest
  nameWithType: IniConfigurationTest
  fullName: Microsoft.Extensions.Configuration.Ini.Test.IniConfigurationTest
