### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables
  commentId: N:Microsoft.Extensions.Configuration.EnvironmentVariables
  id: Microsoft.Extensions.Configuration.EnvironmentVariables
  children:
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.EnvironmentVariables
  nameWithType: Microsoft.Extensions.Configuration.EnvironmentVariables
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
references:
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  isExternal: false
  name: EnvironmentVariablesConfigurationProvider
  nameWithType: EnvironmentVariablesConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  isExternal: false
  name: EnvironmentVariablesConfigurationSource
  nameWithType: EnvironmentVariablesConfigurationSource
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
