### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  commentId: T:Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  id: ConfigurationPathTest
  parent: Microsoft.Extensions.Configuration.Test
  children:
  - Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.CombineWithEmptySegmentLeavesDelimiter
  - Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetLastSegmenGetSectionKeyTests
  - Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetParentPathTests
  langs:
  - csharp
  - vb
  name: ConfigurationPathTest
  nameWithType: ConfigurationPathTest
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  type: Class
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: ConfigurationPathTest
    path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
    startLine: 8
  assemblies:
  - Microsoft.Extensions.Configuration.Test
  namespace: Microsoft.Extensions.Configuration.Test
  syntax:
    content: public class ConfigurationPathTest
    content.vb: Public Class ConfigurationPathTest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.CombineWithEmptySegmentLeavesDelimiter
  commentId: M:Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.CombineWithEmptySegmentLeavesDelimiter
  id: CombineWithEmptySegmentLeavesDelimiter
  parent: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  langs:
  - csharp
  - vb
  name: CombineWithEmptySegmentLeavesDelimiter()
  nameWithType: ConfigurationPathTest.CombineWithEmptySegmentLeavesDelimiter()
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.CombineWithEmptySegmentLeavesDelimiter()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: CombineWithEmptySegmentLeavesDelimiter
    path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.Test
  namespace: Microsoft.Extensions.Configuration.Test
  syntax:
    content: >-
      [Fact]

      public void CombineWithEmptySegmentLeavesDelimiter()
    content.vb: >-
      <Fact>

      Public Sub CombineWithEmptySegmentLeavesDelimiter
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetLastSegmenGetSectionKeyTests
  commentId: M:Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetLastSegmenGetSectionKeyTests
  id: GetLastSegmenGetSectionKeyTests
  parent: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  langs:
  - csharp
  - vb
  name: GetLastSegmenGetSectionKeyTests()
  nameWithType: ConfigurationPathTest.GetLastSegmenGetSectionKeyTests()
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetLastSegmenGetSectionKeyTests()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: GetLastSegmenGetSectionKeyTests
    path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
    startLine: 18
  assemblies:
  - Microsoft.Extensions.Configuration.Test
  namespace: Microsoft.Extensions.Configuration.Test
  syntax:
    content: >-
      [Fact]

      public void GetLastSegmenGetSectionKeyTests()
    content.vb: >-
      <Fact>

      Public Sub GetLastSegmenGetSectionKeyTests
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetParentPathTests
  commentId: M:Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetParentPathTests
  id: GetParentPathTests
  parent: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest
  langs:
  - csharp
  - vb
  name: GetParentPathTests()
  nameWithType: ConfigurationPathTest.GetParentPathTests()
  fullName: Microsoft.Extensions.Configuration.Test.ConfigurationPathTest.GetParentPathTests()
  type: Method
  source:
    remote:
      path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: GetParentPathTests
    path: test/Microsoft.Extensions.Configuration.Test/ConfigurationPathTest.cs
    startLine: 32
  assemblies:
  - Microsoft.Extensions.Configuration.Test
  namespace: Microsoft.Extensions.Configuration.Test
  syntax:
    content: >-
      [Fact]

      public void GetParentPathTests()
    content.vb: >-
      <Fact>

      Public Sub GetParentPathTests
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration.Test
  commentId: N:Microsoft.Extensions.Configuration.Test
  isExternal: false
  name: Microsoft.Extensions.Configuration.Test
  nameWithType: Microsoft.Extensions.Configuration.Test
  fullName: Microsoft.Extensions.Configuration.Test
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
