### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  id: ICommonModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Attributes
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.MemberInfo
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Name
  langs:
  - csharp
  - vb
  name: ICommonModel
  nameWithType: ICommonModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: ICommonModel
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
    startLine: 8
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: 'public interface ICommonModel : IPropertyModel'
    content.vb: >-
      Public Interface ICommonModel
          Inherits IPropertyModel
  inheritedMembers:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel.Properties
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Attributes
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Attributes
  id: Attributes
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  langs:
  - csharp
  - vb
  name: Attributes
  nameWithType: ICommonModel.Attributes
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Attributes
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Attributes
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
    startLine: 10
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: IReadOnlyList<object> Attributes { get; }
    content.vb: ReadOnly Property Attributes As IReadOnlyList(Of Object)
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{System.Object}
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.MemberInfo
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.MemberInfo
  id: MemberInfo
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  langs:
  - csharp
  - vb
  name: MemberInfo
  nameWithType: ICommonModel.MemberInfo
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.MemberInfo
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: MemberInfo
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
    startLine: 11
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: MemberInfo MemberInfo { get; }
    content.vb: ReadOnly Property MemberInfo As MemberInfo
    parameters: []
    return:
      type: System.Reflection.MemberInfo
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Name
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Name
  id: Name
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ICommonModel.Name
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel.Name
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Name
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ICommonModel.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: string Name { get; }
    content.vb: ReadOnly Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel.Properties
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel.Properties
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
  isExternal: false
  name: Properties
  nameWithType: IPropertyModel.Properties
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel.Properties
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IPropertyModel
  nameWithType: IPropertyModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
- uid: System.Collections.Generic.IReadOnlyList{System.Object}
  commentId: T:System.Collections.Generic.IReadOnlyList{System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  name: IReadOnlyList<Object>
  nameWithType: IReadOnlyList<Object>
  fullName: System.Collections.Generic.IReadOnlyList<System.Object>
  nameWithType.vb: IReadOnlyList(Of Object)
  fullname.vb: System.Collections.Generic.IReadOnlyList(Of System.Object)
  name.vb: IReadOnlyList(Of Object)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    nameWithType: IReadOnlyList
    fullName: System.Collections.Generic.IReadOnlyList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    nameWithType: IReadOnlyList
    fullName: System.Collections.Generic.IReadOnlyList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullname.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    nameWithType: IReadOnlyList
    fullName: System.Collections.Generic.IReadOnlyList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    nameWithType: IReadOnlyList
    fullName: System.Collections.Generic.IReadOnlyList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Reflection.MemberInfo
  commentId: T:System.Reflection.MemberInfo
  parent: System.Reflection
  isExternal: true
  name: MemberInfo
  nameWithType: MemberInfo
  fullName: System.Reflection.MemberInfo
- uid: System.Reflection
  commentId: N:System.Reflection
  isExternal: false
  name: System.Reflection
  nameWithType: System.Reflection
  fullName: System.Reflection
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
