### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  id: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  - Microsoft.AspNetCore.Mvc.ApplicationModels.AttributeRouteModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IFilterModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.PropertyModel
  - Microsoft.AspNetCore.Mvc.ApplicationModels.SelectorModel
  langs:
  - csharp
  - vb
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
  type: Namespace
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ActionModel
  nameWithType: ActionModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApiExplorerModel
  nameWithType: ApiExplorerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApplicationModel
  nameWithType: ApplicationModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApplicationModelProviderContext
  nameWithType: ApplicationModelProviderContext
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.AttributeRouteModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.AttributeRouteModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: AttributeRouteModel
  nameWithType: AttributeRouteModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.AttributeRouteModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ControllerModel
  nameWithType: ControllerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IActionModelConvention
  nameWithType: IActionModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IApiExplorerModel
  nameWithType: IApiExplorerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  isExternal: false
  name: IApplicationModelConvention
  nameWithType: IApplicationModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IApplicationModelProvider
  nameWithType: IApplicationModelProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IBindingModel
  nameWithType: IBindingModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ICommonModel
  nameWithType: ICommonModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ICommonModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IControllerModelConvention
  nameWithType: IControllerModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IFilterModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IFilterModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IFilterModel
  nameWithType: IFilterModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IFilterModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  isExternal: false
  name: IParameterModelConvention
  nameWithType: IParameterModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IPropertyModel
  nameWithType: IPropertyModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IPropertyModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ParameterModel
  nameWithType: ParameterModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.PropertyModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.PropertyModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: PropertyModel
  nameWithType: PropertyModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.PropertyModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.SelectorModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.SelectorModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: SelectorModel
  nameWithType: SelectorModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.SelectorModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
