### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  id: IApplicationModelProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
  langs:
  - csharp
  - vb
  name: IApplicationModelProvider
  nameWithType: IApplicationModelProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IApplicationModelProvider
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
    startLine: 8
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nBuilds or modifies an <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel\" data-throw-if-not-resolved=\"false\"></xref> for action discovery.\n"
  example: []
  syntax:
    content: public interface IApplicationModelProvider
    content.vb: Public Interface IApplicationModelProvider
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
  id: Order
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  langs:
  - csharp
  - vb
  name: Order
  nameWithType: IApplicationModelProvider.Order
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Order
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
    startLine: 29
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nGets the order value for determining the order of execution of providers. Providers execute in\nascending numeric value of the <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref> property.\n"
  remarks: "\n<p>\nProviders are executed in an ordering determined by an ascending sort of the <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref> property.\nA provider with a lower numeric value of <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref> will have its\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)\" data-throw-if-not-resolved=\"false\"></xref> called before that of a provider with a higher numeric value of\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref>. The <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)\" data-throw-if-not-resolved=\"false\"></xref> method is called in the reverse ordering after\nall calls to <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)\" data-throw-if-not-resolved=\"false\"></xref>. A provider with a lower numeric value of\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref> will have its <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)\" data-throw-if-not-resolved=\"false\"></xref> method called after that of a provider\nwith a higher numeric value of <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref>.\n</p>\n<p>\nIf two providers have the same numeric value of <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref>, then their relative execution order\nis undefined.\n</p>\n"
  example: []
  syntax:
    content: int Order { get; }
    content.vb: ReadOnly Property Order As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  id: OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  langs:
  - csharp
  - vb
  name: OnProvidersExecuting(ApplicationModelProviderContext)
  nameWithType: IApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: OnProvidersExecuting
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
    startLine: 35
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nExecuted for the first pass of <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel\" data-throw-if-not-resolved=\"false\"></xref> building. See <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: void OnProvidersExecuting(ApplicationModelProviderContext context)
    content.vb: Sub OnProvidersExecuting(context As ApplicationModelProviderContext)
    parameters:
    - id: context
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
      description: The <xref href="Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext" data-throw-if-not-resolved="false"></xref>.
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  id: OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  langs:
  - csharp
  - vb
  name: OnProvidersExecuted(ApplicationModelProviderContext)
  nameWithType: IApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: OnProvidersExecuted
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelProvider.cs
    startLine: 41
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nExecuted for the second pass of <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel\" data-throw-if-not-resolved=\"false\"></xref> building. See <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: void OnProvidersExecuted(ApplicationModelProviderContext context)
    content.vb: Sub OnProvidersExecuted(context As ApplicationModelProviderContext)
    parameters:
    - id: context
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
      description: The <xref href="Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext" data-throw-if-not-resolved="false"></xref>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApplicationModel
  nameWithType: ApplicationModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  isExternal: false
  name: Order
  nameWithType: IApplicationModelProvider.Order
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.Order
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  isExternal: false
  name: OnProvidersExecuting(ApplicationModelProviderContext)
  nameWithType: IApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  spec.csharp:
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
    name: OnProvidersExecuting
    nameWithType: IApplicationModelProvider.OnProvidersExecuting
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
    name: ApplicationModelProviderContext
    nameWithType: ApplicationModelProviderContext
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
    name: OnProvidersExecuting
    nameWithType: IApplicationModelProvider.OnProvidersExecuting
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuting
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
    name: ApplicationModelProviderContext
    nameWithType: ApplicationModelProviderContext
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  isExternal: false
  name: OnProvidersExecuted(ApplicationModelProviderContext)
  nameWithType: IApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
  spec.csharp:
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
    name: OnProvidersExecuted
    nameWithType: IApplicationModelProvider.OnProvidersExecuted
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
    name: ApplicationModelProviderContext
    nameWithType: ApplicationModelProviderContext
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext)
    name: OnProvidersExecuted
    nameWithType: IApplicationModelProvider.OnProvidersExecuted
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider.OnProvidersExecuted
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
    name: ApplicationModelProviderContext
    nameWithType: ApplicationModelProviderContext
    fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IApplicationModelProvider
  nameWithType: IApplicationModelProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApplicationModelProviderContext
  nameWithType: ApplicationModelProviderContext
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelProviderContext
