### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
  id: IApplicationFeatureProvider`1
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1.PopulateFeature(System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart},`0)
  langs:
  - csharp
  - vb
  name: IApplicationFeatureProvider<TFeature>
  nameWithType: IApplicationFeatureProvider<TFeature>
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider<TFeature>
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/IApplicationFeatureProviderOfT.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IApplicationFeatureProvider
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/IApplicationFeatureProviderOfT.cs
    startLine: 11
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationParts
  summary: "\nA provider for a given <em>TFeature</em> feature.\n"
  example: []
  syntax:
    content: 'public interface IApplicationFeatureProvider<TFeature> : IApplicationFeatureProvider'
    content.vb: >-
      Public Interface IApplicationFeatureProvider(Of TFeature)
          Inherits IApplicationFeatureProvider
    typeParameters:
    - id: TFeature
      description: The type of the feature.
  nameWithType.vb: IApplicationFeatureProvider(Of TFeature)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider(Of TFeature)
  name.vb: IApplicationFeatureProvider(Of TFeature)
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1.PopulateFeature(System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart},`0)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1.PopulateFeature(System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart},`0)
  id: PopulateFeature(System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart},`0)
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
  langs:
  - csharp
  - vb
  name: PopulateFeature(IEnumerable<ApplicationPart>, TFeature)
  nameWithType: IApplicationFeatureProvider<TFeature>.PopulateFeature(IEnumerable<ApplicationPart>, TFeature)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider<TFeature>.PopulateFeature(System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart>, TFeature)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/IApplicationFeatureProviderOfT.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: PopulateFeature
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/IApplicationFeatureProviderOfT.cs
    startLine: 20
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationParts
  summary: "\nUpdates the <em>feature</em> intance.\n"
  example: []
  syntax:
    content: void PopulateFeature(IEnumerable<ApplicationPart> parts, TFeature feature)
    content.vb: Sub PopulateFeature(parts As IEnumerable(Of ApplicationPart), feature As TFeature)
    parameters:
    - id: parts
      type: System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart}
      description: >
        The list of <xref href="Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart" data-throw-if-not-resolved="false"></xref>s of the

        application.
    - id: feature
      type: '{TFeature}'
      description: The feature instance to populate.
  nameWithType.vb: IApplicationFeatureProvider(Of TFeature).PopulateFeature(IEnumerable(Of ApplicationPart), TFeature)
  fullName.vb: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider(Of TFeature).PopulateFeature(System.Collections.Generic.IEnumerable(Of Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart), TFeature)
  name.vb: PopulateFeature(IEnumerable(Of ApplicationPart), TFeature)
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationParts
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationParts
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: ApplicationPart
  nameWithType: ApplicationPart
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
- uid: System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart}
  commentId: T:System.Collections.Generic.IEnumerable{Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<ApplicationPart>
  nameWithType: IEnumerable<ApplicationPart>
  fullName: System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart>
  nameWithType.vb: IEnumerable(Of ApplicationPart)
  fullname.vb: System.Collections.Generic.IEnumerable(Of Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart)
  name.vb: IEnumerable(Of ApplicationPart)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
    name: ApplicationPart
    nameWithType: ApplicationPart
    fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
    name: ApplicationPart
    nameWithType: ApplicationPart
    fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  - name: )
    nameWithType: )
    fullName: )
- uid: '{TFeature}'
  commentId: '!:TFeature'
  definition: TFeature
  name: TFeature
  nameWithType: TFeature
  fullName: TFeature
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullname.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: TFeature
  isExternal: false
  name: TFeature
  nameWithType: TFeature
  fullName: TFeature
