### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  id: IControllerModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  langs:
  - csharp
  - vb
  name: IControllerModelConvention
  nameWithType: IControllerModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IControllerModelConvention
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
    startLine: 16
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nAllows customization of the of the <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  remarks: "\nTo use this interface, create an <xref href=\"System.Attribute\" data-throw-if-not-resolved=\"false\"></xref> class which implements the interface and\nplace it on a controller class.\n\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention\" data-throw-if-not-resolved=\"false\"></xref> customizations run after\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention\" data-throw-if-not-resolved=\"false\"></xref> customizations and before\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\" data-throw-if-not-resolved=\"false\"></xref> customizations.\n"
  example: []
  syntax:
    content: public interface IControllerModelConvention
    content.vb: Public Interface IControllerModelConvention
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  id: Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ControllerModel)
  nameWithType: IControllerModelConvention.Apply(ControllerModel)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Apply
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
    startLine: 22
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nCalled to apply the convention to the <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: void Apply(ControllerModel controller)
    content.vb: Sub Apply(controller As ControllerModel)
    parameters:
    - id: controller
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
      description: The <xref href="Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel" data-throw-if-not-resolved="false"></xref>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ControllerModel
  nameWithType: ControllerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
- uid: System.Attribute
  commentId: T:System.Attribute
  parent: System
  isExternal: true
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IControllerModelConvention
  nameWithType: IControllerModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  isExternal: false
  name: IApplicationModelConvention
  nameWithType: IApplicationModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IActionModelConvention
  nameWithType: IActionModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
