### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationParts
  id: Microsoft.AspNetCore.Mvc.ApplicationParts
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  - Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager
  - Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart
  - Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  - Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
  - Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationPartTypeProvider
  - Microsoft.AspNetCore.Mvc.ApplicationParts.ICompilationReferencesProvider
  langs:
  - csharp
  - vb
  name: Microsoft.AspNetCore.Mvc.ApplicationParts
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationParts
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts
  type: Namespace
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: ApplicationPart
  nameWithType: ApplicationPart
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: ApplicationPartManager
  nameWithType: ApplicationPartManager
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart
  isExternal: false
  name: AssemblyPart
  nameWithType: AssemblyPart
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: IApplicationFeatureProvider
  nameWithType: IApplicationFeatureProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
  isExternal: false
  name: IApplicationFeatureProvider<TFeature>
  nameWithType: IApplicationFeatureProvider<TFeature>
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider<TFeature>
  nameWithType.vb: IApplicationFeatureProvider(Of TFeature)
  fullname.vb: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider(Of TFeature)
  name.vb: IApplicationFeatureProvider(Of TFeature)
  spec.csharp:
  - uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
    name: IApplicationFeatureProvider
    nameWithType: IApplicationFeatureProvider
    fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  - name: <
    nameWithType: <
    fullName: <
  - name: TFeature
    nameWithType: TFeature
    fullName: TFeature
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider`1
    name: IApplicationFeatureProvider
    nameWithType: IApplicationFeatureProvider
    fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TFeature
    nameWithType: TFeature
    fullName: TFeature
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationPartTypeProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationPartTypeProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: IApplicationPartTypeProvider
  nameWithType: IApplicationPartTypeProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationPartTypeProvider
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.ICompilationReferencesProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.ICompilationReferencesProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: ICompilationReferencesProvider
  nameWithType: ICompilationReferencesProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.ICompilationReferencesProvider
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationParts
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationParts
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts
