### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  id: IApiExplorerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel.ApiExplorer
  langs:
  - csharp
  - vb
  name: IApiExplorerModel
  nameWithType: IApiExplorerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApiExplorerModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IApiExplorerModel
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApiExplorerModel.cs
    startLine: 5
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: public interface IApiExplorerModel
    content.vb: Public Interface IApiExplorerModel
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel.ApiExplorer
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel.ApiExplorer
  id: ApiExplorer
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel
  langs:
  - csharp
  - vb
  name: ApiExplorer
  nameWithType: IApiExplorerModel.ApiExplorer
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApiExplorerModel.ApiExplorer
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApiExplorerModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: ApiExplorer
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApiExplorerModel.cs
    startLine: 7
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: ApiExplorerModel ApiExplorer { get; set; }
    content.vb: Property ApiExplorer As ApiExplorerModel
    parameters: []
    return:
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
  modifiers.csharp:
  - get
  - set
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApiExplorerModel
  nameWithType: ApiExplorerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApiExplorerModel
