### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.IUseWebApiRoutes
  commentId: T:Microsoft.AspNetCore.Mvc.WebApiCompatShim.IUseWebApiRoutes
  id: IUseWebApiRoutes
  parent: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  children: []
  langs:
  - csharp
  - vb
  name: IUseWebApiRoutes
  nameWithType: IUseWebApiRoutes
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.IUseWebApiRoutes
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/IUseWebApiRoutes.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IUseWebApiRoutes
    path: src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/IUseWebApiRoutes.cs
    startLine: 8
  assemblies:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim
  namespace: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  summary: "\nIndicates the controller is in the \"api\" area.\n"
  example: []
  syntax:
    content: public interface IUseWebApiRoutes
    content.vb: Public Interface IUseWebApiRoutes
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  commentId: N:Microsoft.AspNetCore.Mvc.WebApiCompatShim
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  nameWithType: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim
