### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  id: IActionModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  langs:
  - csharp
  - vb
  name: IActionModelConvention
  nameWithType: IActionModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IActionModelConvention
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
    startLine: 16
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nAllows customization of the of the <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  remarks: "\nTo use this interface, create an <xref href=\"System.Attribute\" data-throw-if-not-resolved=\"false\"></xref> class which implements the interface and\nplace it on an action method.\n\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\" data-throw-if-not-resolved=\"false\"></xref> customizations run after\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\" data-throw-if-not-resolved=\"false\"></xref> customications and before\n<xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention\" data-throw-if-not-resolved=\"false\"></xref> customizations.\n"
  example: []
  syntax:
    content: public interface IActionModelConvention
    content.vb: Public Interface IActionModelConvention
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  id: Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ActionModel)
  nameWithType: IActionModelConvention.Apply(ActionModel)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Apply
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
    startLine: 22
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nCalled to apply the convention to the <xref href=\"Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: void Apply(ActionModel action)
    content.vb: Sub Apply(action As ActionModel)
    parameters:
    - id: action
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
      description: The <xref href="Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel" data-throw-if-not-resolved="false"></xref>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ActionModel
  nameWithType: ActionModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
- uid: System.Attribute
  commentId: T:System.Attribute
  parent: System
  isExternal: true
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: IActionModelConvention
  nameWithType: IActionModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  isExternal: false
  name: IParameterModelConvention
  nameWithType: IParameterModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
