### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  commentId: T:Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  id: Program
  parent: Microsoft.Extensions.Caching.SqlConfig.Tools
  children:
  - Microsoft.Extensions.Caching.SqlConfig.Tools.Program.#ctor
  - Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Main(System.String[])
  - Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Run(System.String[])
  langs:
  - csharp
  - vb
  name: Program
  nameWithType: Program
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
      branch: master
      repo: https://github.com/aspnet/Caching.git
    id: Program
    path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
    startLine: 11
  assemblies:
  - Microsoft.Extensions.Caching.SqlConfig.Tools
  namespace: Microsoft.Extensions.Caching.SqlConfig.Tools
  syntax:
    content: public class Program
    content.vb: Public Class Program
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.#ctor
  commentId: M:Microsoft.Extensions.Caching.SqlConfig.Tools.Program.#ctor
  id: '#ctor'
  parent: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  langs:
  - csharp
  - vb
  name: Program()
  nameWithType: Program.Program()
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Program()
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
      branch: master
      repo: https://github.com/aspnet/Caching.git
    id: .ctor
    path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
    startLine: 19
  assemblies:
  - Microsoft.Extensions.Caching.SqlConfig.Tools
  namespace: Microsoft.Extensions.Caching.SqlConfig.Tools
  syntax:
    content: public Program()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Main(System.String[])
  commentId: M:Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Main(System.String[])
  id: Main(System.String[])
  parent: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  langs:
  - csharp
  - vb
  name: Main(String[])
  nameWithType: Program.Main(String[])
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Main(System.String[])
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
      branch: master
      repo: https://github.com/aspnet/Caching.git
    id: Main
    path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
    startLine: 26
  assemblies:
  - Microsoft.Extensions.Caching.SqlConfig.Tools
  namespace: Microsoft.Extensions.Caching.SqlConfig.Tools
  syntax:
    content: public static int Main(string[] args)
    content.vb: Public Shared Function Main(args As String()) As Integer
    parameters:
    - id: args
      type: System.String[]
    return:
      type: System.Int32
  nameWithType.vb: Program.Main(String())
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Main(System.String())
  name.vb: Main(String())
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Run(System.String[])
  commentId: M:Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Run(System.String[])
  id: Run(System.String[])
  parent: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  langs:
  - csharp
  - vb
  name: Run(String[])
  nameWithType: Program.Run(String[])
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Run(System.String[])
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
      branch: master
      repo: https://github.com/aspnet/Caching.git
    id: Run
    path: src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
    startLine: 31
  assemblies:
  - Microsoft.Extensions.Caching.SqlConfig.Tools
  namespace: Microsoft.Extensions.Caching.SqlConfig.Tools
  syntax:
    content: public int Run(string[] args)
    content.vb: Public Function Run(args As String()) As Integer
    parameters:
    - id: args
      type: System.String[]
    return:
      type: System.Int32
  nameWithType.vb: Program.Run(String())
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Extensions.Caching.SqlConfig.Tools.Program.Run(System.String())
  name.vb: Run(String())
references:
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools
  commentId: N:Microsoft.Extensions.Caching.SqlConfig.Tools
  isExternal: false
  name: Microsoft.Extensions.Caching.SqlConfig.Tools
  nameWithType: Microsoft.Extensions.Caching.SqlConfig.Tools
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String[]
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullname.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
