### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools
  commentId: N:Microsoft.Extensions.Caching.SqlConfig.Tools
  id: Microsoft.Extensions.Caching.SqlConfig.Tools
  children:
  - Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Caching.SqlConfig.Tools
  nameWithType: Microsoft.Extensions.Caching.SqlConfig.Tools
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Caching.SqlConfig.Tools
references:
- uid: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  commentId: T:Microsoft.Extensions.Caching.SqlConfig.Tools.Program
  isExternal: false
  name: Program
  nameWithType: Program
  fullName: Microsoft.Extensions.Caching.SqlConfig.Tools.Program
